CREATE TABLE `geogoogael`.`ip2location_records` (
    `IP_RANGE_START` INT(10) UNSIGNED NULL DEFAULT NULL,
    `IP_RANGE_END` INT(10) UNSIGNED NULL DEFAULT NULL,
    `ISO-639-1` VARCHAR(2) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `COUNTRY_NAME` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `REGION_NAME` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `CITY_NAME` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `LATITUDE` FLOAT NULL DEFAULT NULL,
    `LONGITUDE` FLOAT NULL DEFAULT NULL,
    `AREA_CODE` VARCHAR(16) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci',
    `TIMEZONE` VARCHAR(6) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci'
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB;

