LOAD DATA LOCAL INFILE 'database.csv' 
REPLACE INTO TABLE `geogoogael`.`ip2location_records` 
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
(`IP_RANGE_START`, `IP_RANGE_END`, `ISO-639-1`, `COUNTRY_NAME`, `REGION_NAME`, `CITY_NAME`, `LATITUDE`, `LONGITUDE`, `AREA_CODE`, `TIMEZONE`);